<a href="https://colab.research.google.com/github/piusAI/Pytorch-Tutorial-Codemy.com/blob/main/05_Mathmathics_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Math Operations
- add, Subtract, Multiply, Divide, Reminders, Exponents
- shorthand and uh, LongHand
- ReassignMent


In [43]:
import torch
import numpy as np

In [47]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])



In [48]:
#Addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [49]:
#Addition LongHand

torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [50]:
#Subtraction
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [51]:
#Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [52]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [53]:
#Multiplication LongHand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [54]:
#Division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [55]:
#Division LongHand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [56]:
#Remainder Modulus

tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [57]:
#Remainder LongHand
torch.remainder(tensor_b,tensor_a)

# =>Same exactly with Modulus

tensor([0, 0, 1, 0])

In [58]:
#Exponent / power
print(tensor_a**2)
print(torch.pow(tensor_a,tensor_b))

tensor([ 1,  4,  9, 16])
tensor([    1,    64,  2187, 65536])


In [62]:
#Another Way to write LongHand
tensor_a.add(tensor_b)
print(tensor_a)

tensor([1, 2, 3, 4])


In [63]:
tensor_a=tensor_a.add(tensor_b)
print(tensor_a)

tensor([ 6,  8, 10, 12])


In [73]:
# tensor.add(tensor_a,tensor_b)
# => Get error
#tensor라는 Object에 대해서만 호출할 수있는 함수!


# Function
torch.add(tensor_a,tensor_b)
# or
# Method
tensor_a.add(tensor_b)

tensor([11, 14, 17, 20])

아래로 읽기보다 Run한것에 따라 변수가 할당되기도함!

=> Runtime - Run ALL!