<a href="https://colab.research.google.com/github/piusAI/Pytorch-Tutorial-Codemy.com/blob/main/02%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
- A **torch.Tensor** is a multi-dimensional Matrix Containing elemets of a single data type.

 => Scalar일 수 있음

- similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's)
- Defulat Datat type of float 32.
- More suitable For deep learning than a numpy array.

In [ ]:
import torch
import numpy as np

# List

In [ ]:
my_list=[1, 2, 3, 4]
my_list2=[[1,2,3,4],[5,2,5,7],[2,3,4,5]]

print(my_list)
print(my_list2)


[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 2, 5, 7], [2, 3, 4, 5]]


# Numpy Arrays

In [ ]:
np1=np.random.choice(range(1,32),size=(3,4))
print(str(np1)+ "\n" +str(np1.dtype))

np2=np.random.rand(3,4)
print("\n"+str(np2))
print(np2.dtype)


[[ 4 11 26 30]
 [21  6  9 23]
 [ 6 29 28  2]]
int64

[[0.02999598 0.63329702 0.97653302 0.45864545]
 [0.12210615 0.72345196 0.04247802 0.95416669]
 [0.41124821 0.51714426 0.18629775 0.98032876]]
float64


# Tensors
- More Familiar DL

In [ ]:
tensor_2d=torch.randn(3,4)
print(tensor_2d)
print(tensor_2d.dtype)

tensor([[-0.7453, -0.9051, -1.6139,  0.1689],
        [-0.4045,  1.5307,  0.1340,  1.1083],
        [-0.0554,  2.2330, -1.0039, -0.1433]])
torch.float32


In [ ]:
tensor_3d= torch.zeros(2,3,4)

print(tensor_3d)
print(tensor_3d.shape)

# Depth :2
# rows : 3
# Columns : 4

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [ ]:
## Create tensor out of numpy array

my_tensor = torch.tensor(np2)
print(my_tensor)

tensor([[0.0300, 0.6333, 0.9765, 0.4586],
        [0.1221, 0.7235, 0.0425, 0.9542],
        [0.4112, 0.5171, 0.1863, 0.9803]], dtype=torch.float64)


In [ ]:
#Check The Type

print("[Original tensor] :" +str(tensor_3d.dtype))
print("[exchange NP to tensor] :" +str(my_tensor.dtype))

[Original tensor] :torch.float32
[exchange NP to tensor] :torch.float64


Check This => [Tensor Documentation](https://docs.pytorch.org/docs/stable/tensors.html)

Tensor Hold the data in DL!