<a href="https://colab.research.google.com/github/piusAI/Pytorch-Tutorial-Codemy.com/blob/main/03_tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10,20)

print(my_torch)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


# ReShape & View

In [8]:


torch_Reshape=my_torch.reshape(2,5)
print(torch_Reshape)

print(torch_Reshape.shape)

tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([2, 5])


In [22]:
# Reshape if we Don't know the Number of items
## => using -1

my_torch2 = torch.arange(15)
print(my_torch2)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [23]:
my_torch2 = my_torch2.reshape(3,-1)
print(my_torch2)

# using -1, match the Reshape Arg!

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [25]:
##View

my_torch3= torch.arange(10)
print(my_torch3)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [33]:
my_torch3=my_torch3.view(2,-1)
print(my_torch3)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


##Difference Between Reshape & View

https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch


In [45]:
#with reshape and view, they will update

my_torch5 = torch.arange(10)
print(my_torch5)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [46]:
my_torch6=my_torch5.reshape(2,5)
print(my_torch6)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [48]:
my_torch5[1] = 9706
print(my_torch5)

tensor([   0, 9706,    2,    3,    4,    5,    6,    7,    8,    9])


In [49]:
print(my_torch6)

tensor([[   0, 9706,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [51]:
#Slice
my_torch7 = torch.arange(10)
print(my_torch7[2:5])

tensor([2, 3, 4])


In [52]:
#Grab slice
my_torch8= my_torch7.reshape(5,-1)
print(my_torch8)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [58]:
print(my_torch8[:,1])
# :,1 => Return the Columns 1

tensor([1, 3, 5, 7, 9])


In [61]:
#Return Column Maintain Original Column
print(my_torch8[:,1:])

tensor([[1],
        [3],
        [5],
        [7],
        [9]])


In [76]:
#test

my_torch10 = torch.arange(40)
my_torch10 = my_torch10.view(4,-1)

print(my_torch10)
print(my_torch10[:,4:])
print(my_torch10[:,4])

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
tensor([[ 4,  5,  6,  7,  8,  9],
        [14, 15, 16, 17, 18, 19],
        [24, 25, 26, 27, 28, 29],
        [34, 35, 36, 37, 38, 39]])
tensor([ 4, 14, 24, 34])
